targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swaggers/"
          output_folder: "lib/swaggers/generated/"